### ISSUE TITLE
fonnts issue

### ISSUE THREAD

**Issue by abitofalchemy** [mrzool/invoice-boilerplate#15]
Error producing PDF.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "Hoefler Text" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.26 ...Common}, Numbers={OldStyle}]{Hoefler Text}

makefile:6: recipe for target 'output.pdf' failed
make: *** [output.pdf] Error 43

**Comment by abitofalchemy** [comment]
is there a quick fix for this, i'm on an ubuntu box.

**Comment by mrzool** [comment]
The quick fix would be to use a font that you have available on your system, and not one that you don't have.

**Comment by sigstart** [comment]
I compile using Ubuntu on Windows Subsystem for Linux and ended up switching to **Georgia** for my serif font, and **Roboto** for my sans-serif font.

If you're using Ubuntu proper (and not WSL), then you can apparently get Georgia by running the MSCoreFonts installer:

```sh
sudo apt install ttf-mscorefonts-installer
```

You'll have to accept a Microsoft EULA, though.

I tried several serif fonts and none of them are a solid replacement for _Hoefler Text_. Surprisingly few of them have support for the smallcaps used in this template.

For awhile I used _Noto Serif_ and _PT Sans_, but _Noto Serif_ doesn't have those cool Old Style numerals that you get in _Hoefler Text_. **Georgia** does, which is why I ended up using it.

An alternative for the sans-serif fonts I mentioned is _Segoe UI_, which comes with Windows Vista and newer. However, it is not included with the MSCoreFonts installer on Ubuntu.

FWIW, I tested Roboto and Segoe UI and ended up liking Roboto more.

P.S. For those who are using WSL, you can access your Windows fonts by creating `/etc/fonts/local.conf` as follows:

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <dir>/mnt/c/Windows/Fonts</dir>
</fontconfig>
```
